### ISSUE TITLE
-webkit-box

### ISSUE THREAD

**Issue by evensandbox** [evensandbox/blog#145]
自己家的浏览器不支持 display: flex; 只好使用 display: -webkit-box; 一直以为 display: flex; 仅仅是 display: -webkit-box; 的新语法糖.

因为记不住 -box- 相关属性, 翻看了 @eric 大大公司 UED 搞的 [webkit CSS Library](http://ued.ctrip.com/webkitcss/index.html).  :+1:  

在 [box-flex](http://ued.ctrip.com/webkitcss/prop/box-flex.html) 页面看到被 mark 的一句话"如何分配其剩余空间". 而 display: flex; 是分配剩余空间. 他们俩还是有区别的.

把我的场景提出来, 看这里 http://jsfiddle.net/redky/9ajep2ar/.  描述下:
- 两头是文本
- 要求左边内容右对齐, 右边内容左对齐.
- 中间是分隔符 - 固定的 120px;
- 中间分隔符要求在容器的正中间.

既然 -webkit-box-flex 作用是分配剩余空间, 那么就想办法不让容器有空余即可. 自然需要使用内容来填充容器, 并且不能让用户看到. OK, 想起在看 oocss 源码时, 用到的 :after 伪元素生成 content. 代码:

``` css
:after {
  // 生成很多内容, 占满空间.
  // 使用空格分隔是为了让它正常换行.
  content: 'X X X X X X X X X X X X X X X X X X ';
  // 放大字体, 减少 X 字符数.
  font-size: 2em;
  // 块元素方便隐藏.
  display: block;
  height: 0; line-height: 0;
  overflow: hidden;
}
```

OK, 问题解决.
