### ISSUE TITLE
inline box - vertical-align

### ISSUE THREAD

**Issue by evensandbox** [evensandbox/blog#146]
前提概要：inline-box 相关内容 [CSS - inline-box](http://zhanhongtao.github.io/blog/ppt/css.html#inline-box)

遇到下面需求:

``` HTML
<button>[Image-default]文本</button>
```

点击后,

``` HTML
<button>[image-Loading]文案</button>
```

最开始 image 内容使用 CSS 背景来填写的: 

``` CSS
button:before {
  content: '';
  display: inline-block; /* 保证和后面内容在一行 */
  width: 16px;
  height: 16px; /* 保证可以放 background */
  background: url(../images/image.png) no-repeat 0 0;
}
```

以上代码, 效果为 image 和 文本没有居中对齐 :-1:   见[这里](http://jsfiddle.net/redky/6pt9etcn/)第二个.

由于它们都是 inline box,  所以添加 vertical-align: middle; 让 image 和文案居中对齐, 即:

``` CSS
button:before {
  ...
  vertical-align: middle;
}
```

但是还是没有对齐, :-1:   

最后为文案包一层 `<span>` 再设置 CSS.

``` HTML
<button><span>文案</span></button>
```

``` CSS
span { vertical-align: middle; }
```

[这里看效果](http://jsfiddle.net/redky/6pt9etcn/)

:+1:
