### ISSUE TITLE
让元素不可见的几种方法

### ISSUE THREAD

**Issue by evensandbox** [evensandbox/blog#153]
在 Web 中, 会存在一些特殊情况, 不让用户看到部分内容或为了效果有目的地做一些隐藏. 隐藏元素的方法有多种, 可在不同情况下针对性使用。 下面做一些总结:
## display: none;

这个最容易想到, 它就是专业做隐藏内容的, 包括子元素同样会被隐藏.

``` css
selector {
  display: none;
}
```
## overflow: hidden

超出容器部分隐藏.

``` css
selector {
  width: 100px; // 设置为 0 时, 完全隐藏
  height: 100px;
  position: relative; // 配合 position 后可隐藏子元素任意内容; 否则, absolute 元素可溢出;
  overflow: hidden;
}
```

比如最近用了下面代码, 来隐藏文本但占有宽度：

``` css
selector:after {
  content: 'X X X X X X X X X X X X X X X X X X X X ';
  line-height: 0;
  height: 0;
  display: block;
  overflow: hidden;
}
```
## opacity: 0

让元素完全透明,  元素会占有位置, 但用户看不到. 或者 color 和 background 颜色相同; 或者让 color 透明(rgba); 
这种方法在覆盖 input[type=file] 时, 会使用到。

``` css
selector {
  opacity: 0;
  filter: alpha(opacity=0);
}
```
## visibility: hidden

和 opacity **类似**.  占有原来的位置.
但元素上绑定的事件不再处理. 
和 display: none 有一些不同, 设置 visibility: hidden 的子元素可以再次设置 visibility: visible 而让元素可见.

``` css
selector {
  visibility: hidden;
}
```
## 让元素偏离“可视窗口”

可视窗口, 可以是 viewport 或者设置了 overflow: hidden 的父容器。

``` css
selector {
  position: fixed;
  right: -1000em; // left: -1000em;
}
```

或者下面方法， 在做图片替换文字时使用.

``` css
selector {
  text-indent: -1000em;
}
```
## clip: rect(0, 0, 0, 0)

使用 clip 裁剪, 裁剪区域足够小, 以至于肉眼看不到。在做三角箭头或者椭圆突出效果是会用到。

``` css
selector {
  position: absolute;
  #clip: rect( 0 0 0 0);
  clip: rect(0, 0, 0, 0);
}
```
## z-index: -1;

让元素在最下层.

``` css
selector {
  position: relative; // absolute/fixed
  z-index: -1;
}
```
## transform: rotate(90deg)

让元素沿着 X/Y 轴旋转 90deg 后, 就看不到了。

``` css
selector {
  transform: rotateX(90deg);
}
```
## transform: sacle(0) 或者 zoom: 0.0000000000000000000000000000001

缩小元素到不可见

``` css
selector {
  transform: sacle(0);
}
```
## transform: rotate(>=90deg) + backface-visibility

``` css
selector {
  transform: rotateY(180deg);
  backface-visibility: hidden;
}
```
