### ISSUE TITLE
实现左右两栏布局, 两栏登高的几种方法

### ISSUE THREAD

**Issue by evensandbox** [evensandbox/blog#154]

**Comment by evensandbox** [comment]
## padding-bottom + margin-bottom

``` css
.wrap {
  overflow: hidden;
}

.side,
.main {
  padding-bottom: 1000em; /* 够使用即可 */
  margin-bottom: -1000em;
}
```

[实例](http://jsfiddle.net/redky/pneb30ov/embedded/result/)

## 使用辅助元素

``` css
.wrap {
  position: relative;
  overflow: hidden;
}
.sideHelper,
.mainHelper {
  position: aboslute;
  left: 0;
  top: 0;
}
.sideHelper {
  z-index: 2; /* 覆盖 .mainHelper */
  width: 200px; /* $sideWidth */
  background-color: #faa;
}
.mainHelper {
  width: 100%;
  background-color: #f1f1f1;
}

/* 其他内容的 z-index 要高于 helper 元素 */
```

[实例](http://jsfiddle.net/redky/0s86znt1/embedded/result/)

## Flex 子元素拉伸

没什么代码, 直接看[实例](http://jsfiddle.net/redky/8aaxptng/embedded/result/)吧!

## display: table/table-cell;

table 标签里面的 td 就是等高的. 看[实例](http://jsfiddle.net/redky/564s0m5d/embedded/result/)

## 其它

使用一个颜色分割的两栏背景图片.
