### ISSUE TITLE
normalize.css

### ISSUE THREAD

**Issue by evensandbox** [evensandbox/blog#175]
读 normalize.css 时看到一些代码.  它里面的注释值得花时间阅读!

``` css
body {
  font-family: sans-serif;
  // Prevent iOS and IE text size adjust after device orientation change, without disabling user zoom.
  -webkit-text-size-adjust: 100%;
}

button, input, optgroup, select, textarea {
  color: inherit;
  font: inherit;
  margin: 0;
}
```
