### ISSUE TITLE
font-spider

### ISSUE THREAD

**Issue by evensandbox** [evensandbox/blog#183]
## [FontSpider](http://font-spider.org/).

在网页使用特殊**中文字体**(系统中可能不存在, 设计师选择的适合视觉的合适字体), 需要使用 WebFont 技术支持 - `@font-face`.  因为中文字体个数很多(常用 3000 字; 英文类 - 数字/字母/符号), 从而中文字体文件很大(7M左右), 导致网页加载性能很差, 并且严重消耗宽带。

使用背景图片实现效果方案，会存在一些问题：
- 用户不能复制文本
- 位图影响缩放影响
- 同样, 搜索引擎不易抓取和分析图片
- 开发和维护成本高

在少量使用特殊中文样式(一般页面标题/Logo/宣传页会少量使用)时, 可以使用 `@font-face` 技术, 但需要对中文字体文件做处理 - 移除不需要字体，从而减少中文字体文件大小。

Font-Spider 就是解决上面的问题, 在网页中任意使用 `@font-face`, 在写下下面代码情况下，它会：
1. 自动[分析网页](https://github.com/cheeriojs/cheerio)中使用的文本
2. [压缩字体](https://github.com/ecomfe/fontmin) - 备份后, 生成新字体文件
3. 同时解决兼容性问题的字体文件 - SVG 等

``` CSS
/*
  IE6   仅支持 Embedded OpenType(.eot) 格式。
  IE7   仅支持 Embedded OpenType(.eot) 格式。
  IE8   仅支持 Embedded OpenType(.eot) 格式。
  Firefox 3.5   支持 TrueType、OpenType(.ttf, .otf) 格式。
  Firefox 3.6   支持 TrueType、OpenType(.ttf, .otf) 及 WOFF 格式。
  Chrome    支持 TrueType、OpenType(.ttf, .otf) 及 SVG Font(.svg) 格式。
  Safari    支持 TrueType、OpenType(.ttf, .otf) 及 SVG Font(.svg) 格式。
  Opera 支持 TrueType、OpenType(.ttf, .otf) 及 SVG Font(.svg) 格式。

  http://w3help.org/zh-cn/causes/RF1001
*/

@font-face {
  font-family: 'tt';
  /* 
    IE 4 开始支持 @font-face.
    但仅支持 .eot 格式字体 - ms 提供压缩工具将 .ttf 转成 .eot.
    同时 IE 不支持 format 写法.
  */
  src: url('./font/tt.eot');
  src:
    url('./font/tt.eot?#font-spider') format('embedded-opentype'),
    /*
      woff
      内建了压缩功能，因而体积更小、方便下载和传播
      支持元信息数据
    */
    url('./font/tt.woff') format('woff'),
    url('./font/tt.ttf') format('truetype'),
    url('./font/tt.svg') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

设计师的春天：中文WebFont解决方案Font-Spider
