### ISSUE TITLE
单行居中对齐, 多行居左对齐

### ISSUE THREAD

**Issue by evensandbox** [evensandbox/blog#195]
使用元素水平居中的方法有

``` css
block {
  text-align: center;
  /* 使块内具有 inline 性质元素居中 */
}
```

``` css
block {
  width: 200px;
  margin: 0 auto;
  /* 常用 */
}
```

``` css
block {
  display: flex; /* 也可使用 inline-flex */
  justify-content: center;
}
```

``` css
block {
  display: flex;
  element {
    margin: auto; /* element 作用 */
  }
}
```

也就是说, 可以使用上面几个方法来解决题目需求.

``` css
block {
  text-align: center; /* 让子元素(inline性质)居中 */
  element {
    display: inline-block; /* 让子元素(匿名)居左 */
    text-align: left;
  }
}
```

``` css
block {
  display: flex; /* 或 inline-flex */
  justify-content: center;
  /* 
    设置 flex 后, 子元素已居中 flex-item 性质.
    flex-item 会根据自身内容来调整所占尺寸.
    而 justify-content 属性让 flex-item 居中显示.
  */
}
```

``` css
block {
  display: flex; /* 或 inline-flex */
  element {
    margin: auto;
  }
}
```

[原问题](http://mp.weixin.qq.com/s?__biz=MzIyNTA0MTgyNQ==&mid=403704620&idx=1&sn=bb513aae01366398a5e1cfda809d5a07&scene=4#wechat_redirect)
