### ISSUE TITLE
左右布局

### ISSUE THREAD

**Issue by evensandbox** [evensandbox/blog#196]
基于下面 html 代码, 实现左右布局, 要求: **左侧固定宽度, 右侧占满剩余空间**.

``` html
<div class="box">
  <div class="side"></div>
  <div class="main"></div>
</div>
```
- flex - 目前没理由不使用它

``` css
/* 使用 flex */
.flex .box {
  display: flex;
}
.flex .main {
  flex: 1;
  margin-left: 10px;
}
```
- 原始的 table, 现在的 `display: table` 布局

``` css
/* 使用 table */
.table .box {
  display: table;
  width: 100%;
}
.table .side,
.table .main {
  display: table-cell;
}
.table .main {
  border-left: 10px solid #fff;
}
```
- 使用 calc 百度比计算

``` CSS
/* calc */
.calc .side,
.calc .main {
  float: left;
}
.calc .side {
  min-height: 1px;
}
.calc .main {
  width: calc(100% - 250px);
  margin-left: 10px;
}
```
- 使用 `overflow: hidden;` 触发 block formatting context. 

``` css
.overflow .side {
  float: left;
  margin-right: 10px;
  min-height: 1px;
}
.overflow .main {
  overflow: hidden;
}
.overflow .side,
.overflow .main {
  padding-bottom: 1000em;
  margin-bottom: -1000em;
}
.overflow .box {
  overflow: hidden;
}
```
- 使用 `display: table;` 触发 block formatting context.

``` css
.bfctb .side {
  float: left;
  min-height: 120px;
  margin-right: 10px;
}
.bfctb .main {
  display: table;
  height: auto;
  /* font-size: 0; */
}
.bfctb .main:after {
  content: '. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ';
  display: inline-block;
  height: 0;
  line-height: 0;
  font-size: 24px; overflow: hidden;
  visibility: hidden;
}
```

修改结构, 使用双飞翼布局.

``` html
<div class="box">
  <div class="main"><div class="content"></div></div>
  <div class="side"></div>
</div>
```

``` css
.x .main,
.x .side {
  float: left;
}
.x .main {
  width: 100%;
  background-color: transparent;
}
.x .side {
  margin-left: -100%;
  height: 220px;
}
.x .content {
  margin-left: 250px;
  background-color: hsl(270, 60%, 80%);
  height: 120px;
}
```

最后, 如果需要实现左右两块等高的话, flex/table 自然已解决问题, 其它方案可使用下面方案.

``` css
.side,
.content {
  padding-bottom: 1000em;
  margin-bottom: -1000em;
}
.box {
  overflow: hidden;
}
```
