### ISSUE TITLE
水平居中方案

### ISSUE THREAD

**Issue by evensandbox** [evensandbox/blog#199]
元素满足以下条件：
- 固定(fixed)在页面顶部
- 视觉宽度随内容自适应, 但存在最大宽度(60%)
- 上面的视觉宽度指, 只有内容下有背景色

技术方案：

``` scss
.box {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%; // 固定位置, 并占满整个空间
  text-align: center; // 让子元素(inline/inline-block)居中
  // 设置高度为 0, 防止内容外区域覆盖页面本身内容
  // 超出内容会自动显示
  height: 0;
}

.inner {
  // inline-block 性质元素, 自动水平居中
  // 支持设置 box 相关属性
  display: inline-block;
  max-width: 60%;
  // 其他样式细节
  padding: 5px 10px;
  background: #000;
  color: #fff;
}
```

[DEMO](http://blog.x181.cn/fe/message.html)
